### ISSUE TITLE
[BUG] copypaste not working, erroring out, custom datapack biomes

### ISSUE THREAD

**Issue by LadyHaley** [toppev/strikepractice-public#28]
**Describe the bug**
I beleive the plugin gets upset if there is a custom datapack biome either within the existing arena or the location its moving to, im not sure

**To Reproduce**
1. Build an arena in a custom datapack biome
2. attempt to copypaste the arena
3. console error

**Expected behavior**
The arena gets copy pasted

**Screenshots**
![image](https://github.com/toppev/strikepractice-public/assets/3754909/739afd3e-3c98-4c01-9ae5-713d8bb91dc6)

**Errors and console logs**
```
[00:08:41 INFO]: LadyHaley issued server command: /arena copypaste basketball
[00:08:44 WARN]: [StrikePractice] Task #40679 for StrikePractice v3.8.1-SNAPSHOT generated an exception
java.lang.IllegalArgumentException: Cannot set the biome to CUSTOM
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftRegionAccessor.setBiome(CraftRegionAccessor.java:237) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.setBiome(CraftBlock.java:356) ~[paper-1.20.1.jar:git-Paper-196]
        at ga.strikepractice.arena.a$1.run(ArenaCommand.java:244) ~[strikepractice-3.8.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Checklist**
- [ Yes ] The issue occurs on latest version of StrikePractice.
- [ No ] The issue occurs without other plugins (or non-official addons).
- [ Yes ] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [ Yes ] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version 1.20.1 Paper Build #196
 - Client version 1.20.1 Fabric with collection of mods
 - Other version [e.g. Database, addons, plugins]

**Other plugins**
AdvancedBan, AdvancedMobArena, ajLeaderboards, ArmorStandAdjustor, ArmorTrimEdit, BanAnnouncer, BannerMaker, BarkBack, BimmCore, BlockEffects, BlockLocker, BlueMap, BlueMap-BannerMarker, BlueMap-Marker, BlueMapSignMarkers, Brewery, ChatColor, Citizens, CitizensCMD, ClearLag, CMILib, CoreProtect, CreeperRecover, CustomCrafting, CustomizablePlayerModels, DamageHolo, DeluxeMentions, DiscordSRV, DiscordSRVUtils, DiscordWhitelister, DropEdit2, DtlPlayershops, dtlTraders, Dualhorse, DurabilityAlert, EasyReferral, eGlow, emotecraft, EnchantGui, EntityTraveller, ExcellentCrates, ExcellentEnchants, ExtractableEnchantments, FastAsyncWorldEdit, FlipCard, FlowerMeal, GCore, Gender, GolfParty, GSit, Harbor, HeadDatabase, HideAndSeek, HolographicDisplays, HoloPlots, HorseChestSaddle, IllegalStack, InteractionVisualizer, InteractiveBooks, InteractiveChat, InteractiveChatDiscordSrvAddon, InvisibleItemFrames, Jobs, LibsDisguises, LoneLibs, Lootin, LuckPerms, Magic, MapModCompanion, MarriageMaster, MCGBluemapEssentialsPlus, McInfected, mcMMO, MiniBoardGames, MinigameMaker, MinionsAndHunger, Multiverse-Core, Multiverse-Inventories, MyPet, MythicMobs, MythicMobsExtension, NexEngine, NoBlackSky, NoteBlockAPI, OreAnnouncer, PacketListenerApi, Paintball, Pazaak, PeacefulPlayerRepacified, PerWorldPlugins, PhantomSpawnControl, PhatLoots, PlaceholderAPI, Plan, PlayerParticles, PlayTime, PlotSquared, PlugManX, ProNouns, ProtectionLib, ProtocolLib, PyroFishingPro, PyroLib, PyroMining, QualityArmory, QualityArmoryVehicles2, QuestCreator, RandomOccurrences, RPGBank, SafeNBT, Sentinel, ServerListPlus, ServerSigns, Shopkeepers, ShulkerRespawner, SkinsRestorer, SmileCore, SpawnerMeta, Spicord, StrikePractice, StripArmour, SunLight, SurvivalGames, Tether, TetrisFriends, TNTRun_reloaded, TogglePvp, VampireRevamp, Vault, ViaBackwards, ViaVersion, Vivecraft-Spigot-Extensions, VoidGen, Votifier, VotingPlugin, WanderingTrades, Werewolf, WolfyUtilities, WorldBorder, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, XConomy, XPBoost, YamipaPlugin

**Additional context**

**Comment by LadyHaley** [comment]
I used world edit to change the biome in the existing arena to a vanilla one, it resolved the issue, but still a pain to come across lol

**Comment by toppev** [comment]
Fixed in devbuilds and in next spigot update (it just won't set the biome if it can't so it will still continue copy pasting)
