### ISSUE TITLE
[BUG] Error with citizens

### ISSUE THREAD

**Issue by dumbo-the-developer** [toppev/strikepractice-public#29]
**Describe the bug**
When player is doing bot duels then spam is occurring in console

**Checklist**
- [ ] The issue occurs on latest version of StrikePractice.
- [ ] The issue occurs without other plugins (or non-official addons).
- [ ] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [ ] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version [e.g. 1.8.8 paper spigot (not fork)]
 - Client version [e.g. optifine 1.8.8]
 - Other version [e.g. Database, addons, plugins]

**Error log**
1:19:48 INFO]: Created a User for BOT_BBAGOD69 (00a884a6-924f-22c1-b5b1-469c51afcb1a) for non Bukkit type: net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC$PlayerNPC
[21:21:34 ERROR]: Could not pass event NPCDespawnEvent to Citizens v2.0.33-SNAPSHOT (build 3260)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-535480ec]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-PaperSpigot-535480ec]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-535480ec]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[server.jar:git-PaperSpigot-535480ec]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-PaperSpigot-535480ec]
        at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:89) ~[?:?]
        at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:326) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-535480ec]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-PaperSpigot-535480ec]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-535480ec]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[server.jar:git-PaperSpigot-535480ec]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-PaperSpigot-535480ec]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:425) ~[server.jar:git-PaperSpigot-535480ec]
        at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.die(EntityHumanNPC.java:144) ~[?:?]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:845) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:805) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:504) ~[server.jar:git-PaperSpigot-535480ec]
        at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:128) ~[?:?]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1006) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1394) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[server.jar:git-PaperSpigot-535480ec]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:864) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:799) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:635) ~[server.jar:git-PaperSpigot-535480ec]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$0(MinecraftServer.java:135) ~[server.jar:git-PaperSpigot-535480ec]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getEntityId()" because the return value of "net.citizensnpcs.api.npc.NPC.getEntity()" is null
        at net.citizensnpcs.ProtocolLibListener.onNPCDespawn(ProtocolLibListener.java:269) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-535480ec]
        ... 37 more

**Comment by toppev** [comment]
This does not seem to be anything with StrikePractice specifically.
It may also be related to ProtocolLib version, if it's a custom spigot or the citizens version. The test server uses an old version (Citizens v2.0.16-SNAPSHOT (build 1267)) and that works fine on 1.8.8 paper.
