### ISSUE TITLE
[BUG] Event Error

### ISSUE THREAD

**Issue by BlockCreator001** [toppev/strikepractice-public#9]
**Describe the bug**
When I start the server

**To Reproduce**
2. Do '....'
3. Then '....'
4. See that '....' happens

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/62543902/182036941-1d75a80d-9f89-4bec-84a3-7cfac471431c.png)

**Errors and console logs**
[18:47:34] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to StrikePractice v3.4.6-SNAPSHOT
java.lang.NoSuchMethodError: 'void org.bukkit.event.world.ChunkUnloadEvent.setCancelled(boolean)'
	at ga.strikepractice.h.d.onChunkUnload(ChunkKeeper.java:66) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor509.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-790]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.Chunk.unloadCallback(Chunk.java:906) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$7(PlayerChunk.java:609) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:619) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.ChunkMapDistance.a(ChunkMapDistance.java:126) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:665) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1072) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1057) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1240) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:762) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1495) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Checklist**
- [ ] The issue occurs on latest version of StrikePractice.
- [ ] The issue occurs without other plugins (or non-official addons).
- [ ] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [ ] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version [paper 1.16.5]
 - Client version [1.19]
 - Other version [e.g. Database, addons, plugins]

**Other plugins**
![image](https://user-images.githubusercontent.com/62543902/182037085-e3e289a5-5730-4466-a9a6-10e46dec4dba.png)

**Additional context**

**Comment by toppev** [comment]
Disable ```keep-chunks-loaded``` in the config.yml. You can still keep ```keep-arenas-loaded: true```

I have plans removing the keep-chunks-loaded option anyway as it causes more problems
